In [1]:
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer

pygame 2.1.2 (SDL 2.0.18, Python 3.8.12)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r'C:\Users\sanskriti sidola\Desktop\Drowsiness_Detection\models\model.h5')

In [14]:
mixer.init()
sound = mixer.Sound(r'C:\Users\sanskriti sidola\Desktop\Drowsiness_Detection\alarm.wav')
cap = cv2.VideoCapture(0)
Score = 0
while True: 
    ret, frame = cap.read()
    height,width = frame.shape[0:2] 
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)
    
    cv2.rectangle(frame, (0,height-50),(250,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=5)
    
    for (ex,ey,ew,eh) in eyes:
        #cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (147,20,255), thickness=5)
        eye= frame[ey:ey+eh,ex:ex+w]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        prediction= model.predict(eye)
        print(prediction)
        
        # if eyes are closed
        if prediction[0][0]>0.10:
            cv2.putText(frame,'CLOSED',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(0,0,255),
                       thickness=2,lineType=cv2.LINE_AA)
            cv2.putText(frame,' Score-'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(0,255,255),
                       thickness=2,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>10):
                try:
                    sound.play()
                except:
                    pass
            
        # if eyes are open
        elif prediction[0][1]>0.10:
            cv2.putText(frame,'OPEN',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(50,205,50),
                       thickness=2,lineType=cv2.LINE_AA)
            cv2.putText(frame,' Score-'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(147,20,255),
                       thickness=2,lineType=cv2.LINE_AA),
            Score = Score-1
            if (Score<0):
                Score=0
        
    cv2.imshow('frame', frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

[[0.13048215 0.8695178 ]]
[[0.00532866 0.9946714 ]]
[[0.66103417 0.33896586]]
[[8.9045003e-05 9.9991095e-01]]
[[0.04249077 0.9575092 ]]
[[0.96015793 0.03984202]]
[[0.48512375 0.51487625]]
[[1.2017462e-05 9.9998796e-01]]
[[9.9943405e-01 5.6587561e-04]]
[[0.06114797 0.938852  ]]
[[0.5630437  0.43695635]]
[[0.00604785 0.9939521 ]]
[[0.02502967 0.97497034]]
[[0.02737478 0.97262526]]
[[0.13973121 0.8602688 ]]
[[0.8938515  0.10614847]]
[[7.7472105e-11 1.0000000e+00]]
[[6.343480e-06 9.999937e-01]]
[[1.000000e+00 8.280751e-11]]
[[0.00376688 0.99623317]]
[[2.9376772e-06 9.9999702e-01]]
[[1.8963653e-06 9.9999809e-01]]
[[3.1425145e-07 9.9999964e-01]]
[[3.2339739e-07 9.9999964e-01]]
[[0.0016327  0.99836737]]
[[0.9964902  0.00350984]]
[[7.1738046e-05 9.9992824e-01]]
[[0.03234458 0.9676555 ]]
[[1.3778202e-04 9.9986219e-01]]
[[0.08994573 0.91005427]]
[[0.01101116 0.9889888 ]]
[[0.00868255 0.9913175 ]]
[[0.18063566 0.81936437]]
[[0.24013332 0.7598667 ]]
[[6.5389531e-06 9.9999344e-01]]
[[5.016924e-09 1